name: Compress Images & Generate CDN Links

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.gif'
  push:
    branches:
      - main
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.gif'
  workflow_dispatch:

jobs:
  compress:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: "85"
          pngQuality: "85"
          webpQuality: "85"
          ignorePaths: "node_modules/**,build/**,.github/**"

      - name: Create Pull Request with Compressed Images
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Auto-compress Images'
          branch-suffix: timestamp
          commit-message: 'Optimize images via calibreapp/image-actions'
          body: |
            ${{ steps.calibre.outputs.markdown }}
            
            ---
            ### CDN Links Ready
            合并后可通过 jsDelivr 访问：
            ```
            https://cdn.jsdelivr.net/gh/${{ github.repository }}/path/to/image.jpg
            ```
          labels: |
            automated
            image-optimization

      - name: Comment CDN Links on PR
        if: github.event_name == 'pull_request' && steps.calibre.outputs.markdown != ''
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const imageFiles = files.filter(f => 
              /\.(jpg|jpeg|png|webp|gif)$/i.test(f.filename)
            );
            
            if (imageFiles.length === 0) return;
            
            const cdnLinks = imageFiles.map(f => {
              const filename = f.filename.split('/').pop();
              return `**${filename}**: \n\`https://cdn.jsdelivr.net/gh/${{ github.repository }}/${f.filename}\``;
            }).join('\n\n');
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## jsDelivr CDN Links\n\n${cdnLinks}\n\n> 合并到 main 分支后即可生效`
            });
